### ISSUE TITLE
Need comid.runs-on relation between CoMID to CoMID

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats/ietf-corim-cddl#26]
As CoMID also models Embedded firmware, an accurate model may need comid.runs-on relationship to the parent Hardware RoT on which the firmware is executed.

**Comment by thomas-fossati** [comment]
as discussed, at this point in time we cannot think of a compelling use case for this.  One could go CoSWID using the new runs-on relation (and add the necessary profiling to CoSWID in order to support non-file-system backed SW).  The other point discussed was the possibility to add the proposed semantics in the future, which is possible given the existence of an extension point.
