### ISSUE TITLE
have `one-or-more<COSE_Key>` instead of `COSE_KeySet` ?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats/ietf-corim-cddl#48]
as per $title -- seems more coherent with the rest.

No strong opinions though.

**Comment by nedmsmith** [comment]
That would allow me to simplify the tables in Endorsement spec – could just declare it “+” of COSE_Key

From: Thomas Fossati ***@***.***>
Reply-To: ietf-rats/ietf-corim-cddl ***@***.***>
Date: Thursday, April 29, 2021 at 7:57 AM
To: ietf-rats/ietf-corim-cddl ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ietf-rats/ietf-corim-cddl] have `one-or-more<COSE_Key>` instead of `COSE_KeySet` ? (#48)


as per $title -- seems more coherent with the rest.

No strong opinions though.
